services:
  - type: web
    name: ai-content-optimizer
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --preload --log-level info --access-logfile - --error-logfile -
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        value: ai-content-optimizer-secret-key-2025
      - key: FLASK_ENV
        value: production
