services:
  - type: web
    name: ai-content-optimizer
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        value: ai-content-optimizer-secret-key-2025
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "0"
